/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

export interface SystemStatus {
  cpu_usage: number
  memory_usage: number
  uptime: number
  processes: Array<string>
  active_users: number
  status_message: string
}

export function fibonacci(n: number): number
export function processText(input: string): string
export function parseJson(jsonStr: string): string
export function getSystemStatus(): SystemStatus
export function renderServerView(width: number, height: number): string
