/* auto-generated by NAPI-RS */

export interface SystemStatus {
  cpuUsage: number;
  memoryUsage: number;
  uptime: number;
  processes: string[];
  activeUsers: number;
  statusMessage: string;
}

export interface FileEntry {
  name: string;
  isDir: boolean;
  size: number;
}

export interface LayoutResult {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface LayoutNodeResult {
  id: number;
  layout: LayoutResult;
  children: LayoutNodeResult[];
}

export interface LayoutStyle {
  width?: number;
  height?: number;
  minWidth?: number;
  minHeight?: number;
  maxWidth?: number;
  maxHeight?: number;
  flexGrow?: number;
  flexShrink?: number;
  flexBasis?: number;
  flexDirection?: string;
  justifyContent?: string;
  alignItems?: string;
  alignContent?: string;
  alignSelf?: string;
  flexWrap?: string;
  gap?: number;
  rowGap?: number;
  columnGap?: number;
  paddingTop?: number;
  paddingRight?: number;
  paddingBottom?: number;
  paddingLeft?: number;
  marginTop?: number;
  marginRight?: number;
  marginBottom?: number;
  marginLeft?: number;
  borderTop?: number;
  borderRight?: number;
  borderBottom?: number;
  borderLeft?: number;
  position?: string;
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
}

export interface LayoutNode {
  id: number;
  style: LayoutStyle;
  children: LayoutNode[];
}

export function getSystemStatus(): SystemStatus;
export function renderServerView(width: number, height: number): string;
export function readDir(path: string): FileEntry[];
export function readFile(path: string): string;
export function fuzzyMatch(query: string, items: string[]): string[];
export function highlightCode(content: string, extension: string): string;
export function processText(input: string): string;
export function parseJson(jsonStr: string): string;
export function computeLayout(
  root: LayoutNode,
  availableWidth: number,
  availableHeight: number,
): LayoutNodeResult;
export function createLayoutNode(style: LayoutStyle): LayoutNode;
