/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Linux: detection of musl is handled by napi-rs usually,
  // but for this simple loader we can assume glibc unless specified.
  // We will just load the local binary which we know matches the environment.
  return false
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./openterminal-ui-core.android-arm64.node')
          } else {
            nativeBinding = require('@openterminal-ui/core-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./openterminal-ui-core.android-arm-eabi.node')
          } else {
            nativeBinding = require('@openterminal-ui/core-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.win32-x64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./openterminal-ui-core.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@openterminal-ui/core-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.win32-ia32-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./openterminal-ui-core.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@openterminal-ui/core-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.win32-arm64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./openterminal-ui-core.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@openterminal-ui/core-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./openterminal-ui-core.darwin-universal.node')
      } else {
        nativeBinding = require('@openterminal-ui/core-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./openterminal-ui-core.darwin-x64.node')
          } else {
            nativeBinding = require('@openterminal-ui/core-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.darwin-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./openterminal-ui-core.darwin-arm64.node')
          } else {
            nativeBinding = require('@openterminal-ui/core-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./openterminal-ui-core.freebsd-x64.node')
      } else {
        nativeBinding = require('@openterminal-ui/core-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.linux-x64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./openterminal-ui-core.linux-x64-musl.node')
            } else {
              nativeBinding = require('@openterminal-ui/core-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.linux-x64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./openterminal-ui-core.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@openterminal-ui/core-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.linux-arm64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./openterminal-ui-core.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@openterminal-ui/core-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.linux-arm64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./openterminal-ui-core.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@openterminal-ui/core-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'openterminal-ui-core.linux-arm-gnueabihf.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./openterminal-ui-core.linux-arm-gnueabihf.node')
          } else {
            nativeBinding = require('@openterminal-ui/core-linux-arm-gnueabihf')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { fibonacci, processText, parseJson, getSystemStatus, renderServerView, readDir, readFile, fuzzyMatch, highlightCode } = nativeBinding

module.exports.fibonacci = fibonacci
module.exports.processText = processText
module.exports.parseJson = parseJson
module.exports.getSystemStatus = getSystemStatus
module.exports.renderServerView = renderServerView
module.exports.readDir = readDir
module.exports.readFile = readFile
module.exports.fuzzyMatch = fuzzyMatch
module.exports.highlightCode = highlightCode
