/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let loadError = null

// Platform specific loading logic
// Note: This is a simplified loader for the sandbox environment where we built specifically for Linux x64-gnu.
// In a full production build, NAPI-RS generates complex logic to handle musl/glibc, arm64, windows, etc.

if (platform === 'linux' && arch === 'x64') {
    try {
        // Try loading the gnu binary
        const localPath = join(__dirname, 'openterminal-ui-core.linux-x64-gnu.node')
        if (existsSync(localPath)) {
            nativeBinding = require(localPath)
        } else {
             // Fallback or check for musl if needed (not built here)
             throw new Error(`Native binary not found at ${localPath}`)
        }
    } catch (e) {
        loadError = e
    }
} else {
    loadError = new Error(`Unsupported platform: ${platform} ${arch}. This build currently only supports linux-x64-gnu via local build.`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { fibonacci, processText, parseJson, getSystemStatus, renderServerView } = nativeBinding

module.exports.fibonacci = fibonacci
module.exports.processText = processText
module.exports.parseJson = parseJson
module.exports.getSystemStatus = getSystemStatus
module.exports.renderServerView = renderServerView
