/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

export interface SystemStatus {
  cpu_usage: number;
  memory_usage: number;
  uptime: number;
  processes: Array<string>;
  active_users: number;
  status_message: string;
}

export interface FileEntry {
  name: string;
  is_dir: boolean;
  size: number;
}

export function getSystemStatus(): SystemStatus;
export function renderServerView(width: number, height: number): string;
export function readDir(path: string): Array<FileEntry>;
export function readFile(path: string): string;
export function fuzzyMatch(query: string, items: Array<string>): Array<string>;
export function highlightCode(content: string, extension: string): string;
export function fibonacci(n: number): number;
export function processText(input: string): string;
export function parseJson(jsonStr: string): string;
